name: delete_dev
on:
  delete:

env:
  VERSION: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get version from release branch
      run: echo "VERSION=${GITHUB_BRANCH}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ github.ref_name }}
    - name: If from develop branch, change to latest
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: echo "VERSION=latest" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ github.event.ref }}
    - name: Display version install
      run: echo "Deleting version ${VERSION} in dev.toolkit"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 'AKIAWXY7DGWYB5GTWUX5'
        aws-secret-access-key: ${{ secrets.AWS_TOOLKIT_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy toolbox to S3 bucket
      run: aws s3 rm s3://s3robust-dev.toolkit.illinois.edu/content/$VERSION --recursive
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id E3EJ8O9WXGDQCO --paths "/$VERSION*"