name: delete_develop
on:
  delete:

env:
  VERSION: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get version from release branch
      run: echo "VERSION=${GITHUB_BRANCH}" >> $GITHUB_ENV
      env: 
        GITHUB_BRANCH: ${{ github.ref_name }}
    - name: Display version install
      run: echo "Deleting version ${VERSION} in dev.toolkit"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 'AKIAXNR47MADGK2A4HEW'
        aws-secret-access-key: ${{ secrets.AWS_SECRET_FOR_AKIAXNR47MADGK2A4HEW }}
        aws-region: us-east-2
    - name: Delete S3 bucket
      run: aws s3 rm s3://dev.toolkit.illinois.edu/content/$VERSION --recursive
    - name: Invalidate Cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id E2AF2WM1XJU9VI --paths "/$VERSION*"